#ifndef _H_VARS_
#define _H_VARS_
#include "define.h"
#include "KeyDataStore.h"
#include "ADC.h"
#if(CT_VAR_EXTEND==FALSE)
		#define CT_VAR_NUM 500 
		#define CT_VAR_RUNTIME_NUM 300
				//SYSTEM
	  
		#define VARS_10MSEVENT 225
		#define VARS_100MSEVENT 226
		#define VARS_1SEVENT 227
		#define VARS_COUNTER 228
		#define VARS_DATE 229
		#define VARS_TIME 230

		#define VARS_SYSTEM_OFFSET_XIN 231
		#define VARS_SYSTEM_OFFSET_YOUT (VARS_SYSTEM_OFFSET_XIN + 1) //232
		#define VARS_SYSTEM_OFFSET_AD0 (VARS_SYSTEM_OFFSET_XIN + 2) //233


		#define VARS_SYSTEM_ADVAR_NUM 16
		#define VARS_SYSTEM_OFFSET_TEMPERUATE (VARS_SYSTEM_OFFSET_AD0 + VARS_SYSTEM_ADVAR_NUM) //249


		#define VARS_SYSTEM_TEMPERATE_NUM 16
		#define VARS_SYSTEM_OFFSET_INCOUNT (VARS_SYSTEM_OFFSET_TEMPERUATE + VARS_SYSTEM_TEMPERATE_NUM) //265


		#define VARS_SYSTEM_OFFSET_INNUM 32

		#define VARS_SYSTEM_OFFSET_MOTORA (VARS_SYSTEM_OFFSET_INCOUNT + VARS_SYSTEM_OFFSET_INNUM)//297
		#define VARS_SYSTEM_OFFSET_MOTORB (VARS_SYSTEM_OFFSET_MOTORA + 1)//298
		#define VARS_SYSTEM_OFFSET_MOTORC (VARS_SYSTEM_OFFSET_MOTORB + 1)//299
				

		#define VARS_VOLATILE_OFFSET 300
		#define VARS_VOLATILE_NUM 190
		#define VARS_VOLATILE_OFFSET_XCOUNTTIMER 479
		#define VARS_VOLATILE_OFFSET_XDEBOUNCE 478
		#define VARS_VOLATILE_OFFSET_MB_ADDR 477
		#define VARS_VOLATILE_OFFSET_MB_BAUDRATE 476
		#define VARS_VOLATILE_OFFSET_MB_MASTER 475
		#define VARS_VOLATILE_OFFSET_MB_SENSORNUM 474
		
		#define VARS_VOLATILE_OFFSET_MB_READTYPE 473
		
		#define VARS_VOLATILE_OFFSET_MB_SENSORADDR 472
		#define VARS_VOLATILE_OFFSET_MB_SENSORVARADDR 471
		#define VARS_VOLATILE_OFFSET_MB_SENSORVARNUM 470
		
		#define VARS_VOLATILE_OFFSET_MB_SENSORDESTVAR 469
		#define VARS_VOLATILE_OFFSET_MB_SENSORFLAG 224


		#define VARS_VOLATILE_OFFSET_MB_SENSORSETNUM 5

		#define VARS_VOLATILE_OFFSET_CALRTC_ENABLE 397
		#define VARS_VOLATILE_OFFSET_TEST_PERIOD 396
		#define VARS_VOLATILE_OFFSET_TIME_SIGN 395
		#define VARS_VOLATILE_OFFSET_TIME_DELTA 394
		#define VARS_VOLATILE_OFFSET_TIME_REC 490


		#define VARS_BACKUP_OFFSET 484
		#define VARS_BACKUP_NUM 16

#else
		#define CT_VAR_NUM 800 
		#define CT_VAR_RUNTIME_NUM 500
			//SYSTEM

		#define VARS_10MSEVENT 300
		#define VARS_100MSEVENT 301
		#define VARS_1SEVENT 302
		#define VARS_COUNTER 302
		#define VARS_DATE 303
		#define VARS_TIME 304

		#define VARS_SYSTEM_OFFSET_XIN  305
		#define VARS_SYSTEM_OFFSET_YOUT (VARS_SYSTEM_OFFSET_XIN + 1) //306
		#define VARS_SYSTEM_OFFSET_AD0 (VARS_SYSTEM_OFFSET_XIN + 2) //307


		#define VARS_SYSTEM_ADVAR_NUM 16
		#define VARS_SYSTEM_OFFSET_TEMPERUATE (VARS_SYSTEM_OFFSET_AD0 + VARS_SYSTEM_ADVAR_NUM) //323


		#define VARS_SYSTEM_TEMPERATE_NUM 16
		#define VARS_SYSTEM_OFFSET_INCOUNT (VARS_SYSTEM_OFFSET_TEMPERUATE + VARS_SYSTEM_TEMPERATE_NUM) //339


		#define VARS_SYSTEM_OFFSET_INNUM 32
		//371

		#define VARS_SYSTEM_OFFSET_PC (VARS_SYSTEM_OFFSET_INCOUNT + VARS_SYSTEM_OFFSET_INNUM)
		#define VARS_SYSTEM_OFFSET_PCNUM ROUTINE_NUM
		//395

		#define VARS_SYSTEM_OFFSET_DELAY (VARS_SYSTEM_OFFSET_PC + VARS_SYSTEM_OFFSET_PCNUM)
		#define VARS_SYSTEM_OFFSET_DELAYNUM ROUTINE_NUM
		//419



		#define VARS_SYSTEM_OFFSET_MOTORA 497
		#define VARS_SYSTEM_OFFSET_MOTORB (VARS_SYSTEM_OFFSET_MOTORA + 1)//498
		#define VARS_SYSTEM_OFFSET_MOTORC (VARS_SYSTEM_OFFSET_MOTORB + 1)//499


		#define VARS_VOLATILE_OFFSET 500
		#define VARS_VOLATILE_NUM 290
		#define VARS_VOLATILE_OFFSET_XCOUNTTIMER 789
		#define VARS_VOLATILE_OFFSET_XDEBOUNCE 788
		#define VARS_VOLATILE_OFFSET_MB_ADDR 787
		#define VARS_VOLATILE_OFFSET_MB_BAUDRATE 786
		#define VARS_VOLATILE_OFFSET_MB_MASTER 785
		#define VARS_VOLATILE_OFFSET_MB_SENSORNUM 784


		#define VARS_VOLATILE_OFFSET_MB_SENSORADDR 783
		#define VARS_VOLATILE_OFFSET_MB_SENSORVARADDR 782
		#define VARS_VOLATILE_OFFSET_MB_SENSORVARNUM 781
		#define VARS_VOLATILE_OFFSET_MB_SENSORDESTVAR 780
		#define VARS_VOLATILE_OFFSET_MB_SENSORFLAG 459


		#define VARS_VOLATILE_OFFSET_MB_SENSORSETNUM 4

		#define VARS_VOLATILE_OFFSET_CALRTC_ENABLE 697
		#define VARS_VOLATILE_OFFSET_TEST_PERIOD 696
		#define VARS_VOLATILE_OFFSET_TIME_SIGN 695
		#define VARS_VOLATILE_OFFSET_TIME_DELTA 694
		#define VARS_VOLATILE_OFFSET_TIME_REC 690

		#define VARS_VOLATILE_OFFSET_RESUME_ZID 689
		#define VARS_VOLATILE_OFFSET_RESUME_YOUT 688


		#define VARS_BACKUP_OFFSET 790
		#define VARS_BACKUP_NUM 10 
#endif


extern int g_ct_uiVarComp[CT_VAR_NUM];

#define CT_GET_VAR(index) g_ct_uiVarComp[index]
#define CT_WRITE_VAR(index, var) g_ct_uiVarComp[index] = var


extern void fnVARS_RealTime(void);
extern void fnVARS_Init(void);
extern void fnVARS_SetDefault(void);
extern void fnVARS_Save(U32 varid, U32 value);

#endif 
